version: '3.6'

services:
  db:
    image: mariadb:10.1.41
    volumes:
      - ./database:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 127.0.0.1:5451:3306    
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_DATABASE: mydb
        MYSQL_USER: mydbuser
        MYSQL_PASSWORD: changeme
  
  wordpress:
    build: ./docker
    image: wordpress-myproject
    depends_on:
      - db
    ports:
      - 127.0.0.1:5450:80
    restart: always
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: mydb
        WORDPRESS_DB_USER: mydbuser
        WORDPRESS_DB_PASSWORD: changeme
    volumes:
        - .wordpress/plugins:/var/www/html/wp-content/plugins
        - .wordpress/themes:/var/www/html/wp-content/themes
        - .wordpress/uploads:/var/www/html/wp-content/uploads
